apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-rollupdatekubtest1
  labels:
    app: ddd
    tpaas-app: '91'
    tpaas-controller-kind: daemonset
    tpaas-ns: '31'
  annotations:
    deprecated.daemonset.template.generation: '1'
    tpaas.cloud/create-user: zjj002
spec:
  selector:
    matchLabels:
      app: ddd
      tpaas-app: '91'
      tpaas-controller-kind: daemonset
      tpaas-ns: '31'
  template:
    metadata:
      labels:
        app: ddd
        tpaas-app: '91'
        tpaas-controller-kind: daemonset
        tpaas-ns: '31'
      annotations:
        tpaas.cloud/container-secrets: '{}'
        tpaas.cloud/create-user: zjj002
    spec:
      containers:
        - name: container1
          image: ${DEVOPS_IMAGE_FULL_TAG}
          resources:
            limits:
              cpu: '1'
              memory: 1000Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
  revisionHistoryLimit: 10

